### PR TITLE
Problem: (#12)mnemonic field is accidentally deleted in accounts generation

### PR DESCRIPTION
**Pull request by allthatjazzleo**
Solution: adding back mnemonic field

### CODE REVIEW

**Comment by leejw51crypto** [comment]
it should pass integration test
i'm checking on it

**Comment by leejw51crypto** [comment]
line 255:         # create validator account
        self.create_account("validator", i, mnemonic)
use mnemonics in this way

**Comment by leejw51crypto** [comment]
change pyproject.toml like this
to test

for example)
- from pypi
```
[tool.poetry.dependencies]
pystarport = "^0.2.1"
```
- from GitHub
```
[tool.poetry.dependencies]
pystarport = { git = "https://github.com/crypto-com/pystarport.git", branch ="main"}

```

**Comment by leejw51crypto** [comment]
make nix-integration-test

**Comment by leejw51crypto** [comment]
also for api design perspective,
how about giving mnemonics as argument instead of node.get("mnemonic")?
because mnemonic is special, storing is only for testing 

if pystarport is used not testing, mnemonics are not stored, and given from user.

**Comment by allthatjazzleo** [comment]
> also, check line 255: # create validator account
> self.create_account("validator", i, mnemonic)
> 
> create_account is used like above, need to change this line or other code.

For line 255, it is different method from line 691

**Comment by leejw51crypto** [comment]
yes, that's correct
same name `create_account` in different classes.
maybe we can refactoring later

**Review by leejw51crypto — APPROVED** [review]
lgtm 👍

**Review by yihuang — APPROVED** [review]

**Pull request merged**
