### PR TITLE
support merge client config

### PR DESCRIPTION
**Pull request by alberthuang24**

### CODE REVIEW

**Review by yihuang — APPROVED** [review]

**Review by mmsqe — COMMENTED** [review]
Can you sign the commit?

**Comment by alberthuang24** [comment]
> Can you sign the commit?

done.

**Comment by mmsqe** [comment]
> done.

Seems not [verified](https://docs.github.com/en/authentication/managing-commit-signature-verification/displaying-verification-statuses-for-all-of-your-commits) yet 
Screenshot 2023-03-21 at 11 00 33 AM

**Comment by alberthuang24** [comment]
Oops, now I'm sure it works

**Pull request merged**
