### PR TITLE
Problem: avoid cmd overwritten for all chains

### PR DESCRIPTION
**Pull request by mmsqe**
add ignore_cmd_chain_id

### CODE REVIEW

**Comment by yihuang** [comment]
do you mean in ibc scenario, you only want to override one chain's cmd through cli?

**Comment by mmsqe** [comment]
> do you mean in ibc scenario, you only want to override one chain's cmd through cli? I find the case too specific, one can always do that with a config file override, right?

yes, I need ignore to overwrite [chainmaind](https://github.com/mmsqe/cronos/blob/v0.9.0-beta2/integration_tests/test_upgrade.py#L92) cmd, but I didnt change default behaviour.

**Comment by yihuang** [comment]
> > do you mean in ibc scenario, you only want to override one chain's cmd through cli? I find the case too specific, one can always do that with a config file override, right?
> 
> yes, I need ignore to overwrite [chainmaind](https://github.com/mmsqe/cronos/blob/v0.9.0-beta2/integration_tests/test_upgrade.py#L92) cmd, but I didnt change default behaviour.

but you can simply update the config file? I find the new flag is too specific.

**Comment by mmsqe** [comment]
> but you can simply update the config file? I find the new flag is too specific.

But chainmain's [cmd](https://github.com/mmsqe/cronos/blob/v0.9.0-beta2/integration_tests/configs/ibc.jsonnet#L26) in config is overwritten.

**Comment by yihuang** [comment]
> > but you can simply update the config file? I find the new flag is too specific.
> 
> But chainmain's [cmd](https://github.com/mmsqe/cronos/blob/v0.9.0-beta2/integration_tests/configs/ibc.jsonnet#L26) in config is overwritten.

I mean modify the cronos's cmd in config, rather than using cli flag.

**Comment by mmsqe** [comment]
> I mean modify the cronos's cmd in config, rather than using cli flag.

Not sure if can change that cmd in jsonnet like in upgrade case, chain_binary is generated during test.

**Comment by yihuang** [comment]
> > I mean modify the cronos's cmd in config, rather than using cli flag.
> 
> Not sure if can change that cmd in jsonnet like in upgrade case, chain_binary is generated during test.

do you put multiple chains in the `cosmovisor.yaml`?

**Pull request closed without merging**
