### PR TITLE
release v0.2.2

### PR DESCRIPTION
**Pull request by leejw51crypto**
release v0.0.2

### CODE REVIEW

**Comment by leejw51crypto** [comment]
adding more logs now

**Comment by yihuang** [comment]
Can you also increase the version number in the `pyproject.toml`?

**Comment by leejw51crypto** [comment]
ok

**Comment by yihuang** [comment]
> ok,
> i'll modify chain-main, when pystarport v0.2.2 is ready

hmm, I'm in this repo, we need to increase version number in the `pyproject.toml` file.

**Comment by leejw51crypto** [comment]
ok

**Review by yihuang — APPROVED** [review]

**Pull request merged**
